### ISSUE TITLE
Line numbers alignment

### ISSUE THREAD

**Issue by wassereimer86** [EnlighterJS/Plugin.WordPress#127]
Hello,

i've recognized that the code is not perfectly aligned on the same high when we go from line 9 to 10. I really don´t like it and it's triggering me hard...... :D

![chrome_2018-10-19_01-28-06](https://user-images.githubusercontent.com/22779744/47189790-8ce43800-d33e-11e8-9791-f673784854d9.png)

Would be great to have a solution for this.

Best regards

**Comment by AndiDittrich** [comment]
see #57 

it's related to the css list styles (type: inside/outside) and won't be fixed in the current release

**Comment by wassereimer86** [comment]
Thanks for the information. Is there a plan when v3 will come out? :) It sounds really interesting. :)

**Comment by wassereimer86** [comment]
Yes.... But when as a stable relase and when will the WordPress Plugin be updated to it? Or is it not fixed in v3 yes? Because #57 is closed i assumed that.

**Comment by AndiDittrich** [comment]
> EnlighterJS v3: `Dec. 2018`
> Enlighter v4 WordPress Plugin including EnlighterJS v3: `Q1 2019`

in the meantime you can change the EnlighterJS theme styles on your own :+1:
